#!/usr/bin/env php
<?php

$pluginName = readline('Enter Plugin Name: '); 
$pluginName = ucwords($pluginName);
$pluginDescription = readline('Enter Plugin Description: ');
$pluginDescription = empty($pluginDescription) ? 'This is a plugin' : $pluginDescription;
$pluginAuthor = readline('Enter Plugin Author: ');
$pluginAuthor = empty($pluginAuthor) ? 'Sohag Srz' : $pluginAuthor;
$pluginAuthorURI = readline('Enter Plugin Author URI: ');
$pluginAuthorURI = empty($pluginAuthorURI) ? 'https://sohag.xyz' : $pluginAuthorURI;
$pluginuri = readline('Enter Plugin URI: ');
$pluginuri = empty($pluginuri) ? 'https://sohag.xyz' : $pluginuri;
$pluginVersion = readline('Enter Plugin Version: ');
$pluginVersion = empty($pluginVersion) ? '1.0.0' : $pluginVersion;
$pluginTextDomain = readline('Enter Plugin Text Domain: ');
$pluginTextDomain = empty($pluginTextDomain) ? strtolower(str_replace(' ', '-', $pluginName)) : $pluginTextDomain;
 

$pluginSlug = strtolower(str_replace(' ', '-', $pluginName));

$plugin_key = readline('Enter Plugin Key: ');
$plugin_key = strtoupper(str_replace(' ', '_', $plugin_key));


$plugin_function_key = readline('Enter Plugin Function Key: ');

$plugin_function_key = strtolower(str_replace(' ', '_', $plugin_function_key));

$plugin_file = $pluginSlug . '.php';
//plugin-name.php load
$configfileContents = file_get_contents('plugin-name.php');
$replaceString=  [
    'plugin-name',
    'PLUGIN_NAME_STRING',
    'Plugin_Name',
    'PLUGIN_URI',
    'PLUGIN_DESCRIPTION',
    'PlUGIN_VERSION',
    'PLUGIN_AUTHOR',
    'TEXT_DOMAIN',
    'plugin_name',
];
$replaceStringWith=[
    $pluginSlug,
    $plugin_key,
    $pluginName,
    $pluginuri,
    $pluginDescription,
    $pluginVersion,
    $pluginAuthor,
    $pluginTextDomain,
    $plugin_function_key,
];
$mutedCodes=str_replace( 
    $replaceString,
    $replaceStringWith,
    $configfileContents
);
file_put_contents($plugin_file, $mutedCodes);
// check all files from current dir and dirs if rename file and folder rename and contents update by str_replace
$files = scandir('.');
foreach ($files as $file) {
    if (is_dir($file) && $file != '.' && $file != '..') {
        $newName = str_replace('plugin-name', $pluginSlug, $file);
        rename($file, $newName);
    }
    if (is_file($file) && $file != 'create-plugin.php') {
        $fileContents = file_get_contents($file);
        $newContents = str_replace($replaceString, $replaceStringWith, $fileContents);
        file_put_contents($file, $newContents);
    }
}
// remove create-plugin.php

// remove 
unlink('plugin-name.php');
//remove sohagwp
unlink('sohagwp');
echo "Plugin Created Successfully\n";
echo "Plugin Name: $pluginName\n";
echo "Plugin Description: $pluginDescription\n";
echo "Plugin Author: $pluginAuthor\n";